"use client";
import { FormEvent, useState } from "react";

export default function AdminPage() {
  const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(""); const form=event.currentTarget; const data=new FormData(form); const files=data.getAll("photos") as File[];
    try { const images:string[]=[]; for (const file of files) { const upload=new FormData(); upload.append("file",file); const response=await fetch("/api/upload",{method:"POST",headers:{"x-admin-password":password},body:upload}); const result=await response.json(); if(!response.ok) throw new Error(result.error); images.push(result.url); }
      const response=await fetch("/api/admin/models",{method:"POST",headers:{"content-type":"application/json","x-admin-password":password},body:JSON.stringify({name:data.get("name"),city:data.get("city"),bio:data.get("bio"),images})}); const result=await response.json(); if(!response.ok) throw new Error(result.error); form.reset(); setMessage("Modelo publicada com sucesso.");
    } catch(error){setMessage(error instanceof Error?error.message:"Falha ao salvar.");} finally{setBusy(false);}
  }
  return <main className="admin-page"><a href="/" className="admin-back">← Voltar para a votação</a><section className="admin-panel"><p className="eyebrow">Área da organização</p><h1>Nova finalista</h1><p>Cadastre a modelo e envie as imagens que irão compor o carrossel.</p><form onSubmit={submit}><label>Senha da organização<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label><div className="admin-row"><label>Nome completo<input name="name" required /></label><label>Cidade / Estado<input name="city" required /></label></div><label>Apresentação<textarea name="bio" rows={4} required /></label><label>Fotos do carrossel<input name="photos" type="file" accept="image/*" multiple required /><small>JPG, PNG ou WebP. Até 4 MB por foto.</small></label><button className="primary-button full" disabled={busy}>{busy?"Publicando…":"Publicar finalista"}</button>{message&&<p className="admin-message">{message}</p>}</form></section><style jsx>{`.admin-page{min-height:100vh;background:#eee9df;padding:40px 20px}.admin-back{display:block;max-width:760px;margin:0 auto 25px;font-size:12px}.admin-panel{max-width:760px;margin:auto;background:#faf8f3;padding:clamp(30px,6vw,70px);border:1px solid rgba(17,16,15,.15)}h1{font-size:70px;line-height:.9;margin:8px 0 18px}.admin-panel>p:not(.eyebrow){color:#706a61;margin-bottom:35px}form,label{display:grid;gap:8px}form{gap:22px}label{font-size:11px;text-transform:uppercase;letter-spacing:.12em}.admin-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}input,textarea{width:100%;border:1px solid rgba(17,16,15,.2);background:#fff;padding:14px;font:14px var(--font-sans);text-transform:none;letter-spacing:normal}small{color:#777;text-transform:none;letter-spacing:normal}.admin-message{text-align:center;font-size:13px}@media(max-width:600px){.admin-row{grid-template-columns:1fr}h1{font-size:54px}}`}</style></main>;
}
